### ISSUE TITLE
Adding bars in New-Yorker style puzzle makes letters align differently

### ISSUE THREAD

**Issue by ren-zhou** [djghosh13/druboard#10]
![image](https://user-images.githubusercontent.com/55266596/125123307-7bca4f00-e0c4-11eb-8827-a6be1f6c34fc.png)

**Comment by djghosh13** [comment]
I will have you know this was a _feature_ intended to mimic the style of the New Yorker online crosswords, pictured below
![image](https://user-images.githubusercontent.com/43189945/125126411-eb820f00-e0af-11eb-8c57-88fd8d758fe4.png)

But, if you insist, I will try to match your preferred style of crossword rendering.

**Comment by djghosh13** [comment]
Fixed.
